#:schema node_modules/wrangler/config-schema.json
name = "name-of-your-worker"
main = "src/index.ts"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ROOT_KEY = "your-root-key"
RESEND_KEY = "your-resend-api-key"
JWT_SECRET = "your-jwt-secret"
JWT_REFRESH_SECRET = "your-jwt-refresh"

[[d1_databases]]
binding = "DB"
database_name = "d1-database-name"
database_id = "d1-database-id"
