CREATE TABLE IF NOT EXISTS Users (
	id VARCHAR(100) UNIQUE PRIMARY KEY NOT NULL,
	name VARCHAR(100) NOT NULL,
	lastname VARCHAR(100) NOT NULL,
	nickname VARCHAR(80) NOT NULL,
	pin TEXT NOT NULL,
	birthdate DATE NOT NULL,
	phone VARCHAR(10) UNIQUE NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	avatar TEXT,
	telegramChatId VARCHAR(100) NOT NULL,
	otpCode VARCHAR(6),
	otpExpiration TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Tasks (
	id VARCHAR(100) UNIQUE PRIMARY KEY NOT NULL,
	title VARCHAR(100) NOT NULL,
	content TEXT NOT NULL,
	date TIMESTAMP NOT NULL,
	status VARCHAR(80) NOT NULL,
	userId VARCHAR(100) NOT NULL,
	createdAt TIMESTAMP,
	updatedAt TIMESTAMP,
	FOREIGN KEY (userId) REFERENCES Users(id)
);
